### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by DonRichards** [MikeBarnhardt/citizen#15]
I was able to replicate errors. Not sure if the same issues. 

```
Please fix the errors below.
````

After successfully registering it it redirects to /profile but still has the content component displayed 
in the DOM as /signup

**Client Email:**
_I am trying to utilize your Civics Connection tools but it requires me to log in. When I go to set up an account I fill in every box and it says there is an error at the top but nothing is highlighted or indicated as incorrect._
 
_I am really looking forward to trying to use these materials in the coming week, any advice on how to access your fantastic materials?_
 
_Thank you_

* Note: All red dots seem to imply those fields additional need attention.
* 2nd note: Browser console is displaying "onYouTubeIframeAPIReady called "

**Comment by MikeBarnhardt** [comment]
I can't replicate the problem. Registered 4 separate accounts using different options.

Not enough information given to even begin to diagnose the problem. Please provide client's email address.

**Comment by DonRichards** [comment]
That was all the information given. There was no console.log(err) passed upon this error. I just checked again and it works. Cruze, Kathleen N <cruzek@gcsnc.com>
